MCU        = RP2040
BOOTLOADER = rp2040
LTO_ENABLE = no

SPLIT_KEYBOARD = yes
SERIAL_DRIVER  = pio

RGBLIGHT_SUPPORTED   = yes 
RGB_MATRIX_SUPPORTED = yes 
RGB_MATRIX_DRIVER    = WS2812
WS2812_DRIVER        = pio

# FIXME
ALLOW_WARNINGS          = yes
PICO_INTRINSICS_ENABLED = no

BOOTMAGIC_ENABLE = no
