MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
OLED_DRIVER_ENABLE = no
TAP_DANCE_ENABLE = yes
LEADER_ENABLE = no
# RGB_MATRIX_ENABLE = WS2812

LINK_TIME_OPTIMIZATION_ENABLE = yes

BOOTLOADER = atmel-dfu
